package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	"github.com/lucas4ndrade/FullcycleCleanArch/internal/infra/graph/model"
	"github.com/lucas4ndrade/FullcycleCleanArch/internal/usecase"
)

// CreateOrder is the resolver for the createOrder field.
func (r *mutationResolver) CreateOrder(ctx context.Context, input *model.OrderInput) (*model.Order, error) {
	dto := usecase.CreateOrderInputDTO{
		ID:    input.ID,
		Price: float64(input.Price),
		Tax:   float64(input.Tax),
	}
	output, err := r.CreateOrderUseCase.Execute(dto)
	if err != nil {
		return nil, err
	}
	return &model.Order{
		ID:         output.ID,
		Price:      float64(output.Price),
		Tax:        float64(output.Tax),
		FinalPrice: float64(output.FinalPrice),
	}, nil
}

// Orders is the resolver for the orders field.
func (r *queryResolver) Orders(ctx context.Context, from *int, size *int) (response []*model.Order, err error) {
	inputDTO := usecase.GetDefaultOrderInputDTO()
	if from != nil {
		inputDTO.From = int64(*from)
	}
	if size != nil {
		inputDTO.Size = int64(*size)
	}

	output, err := r.ListOrderUseCase.Execute(inputDTO)
	if err != nil {
		return
	}

	for _, orderDTO := range output {
		o := &model.Order{
			ID:         orderDTO.ID,
			Price:      float64(orderDTO.Price),
			Tax:        float64(orderDTO.Tax),
			FinalPrice: float64(orderDTO.FinalPrice),
		}
		response = append(response, o)
	}
	return
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
